"""Knowledge Base domain model (REFERENCE_GAP_ANALYSIS A1; AutoApply MIT concept).

Career entries the user adds once and reuses across applications: projects,
achievements, stories (STAR), and short blurbs. Selection per JD is done by
TF-IDF cosine similarity over entry text vs the JD text (A4's ATS score is the
same math). Everything is local; nothing here calls the network.

Anti-fabrication rule (R-POLICY-6): entries are USER-ASSERTED content — they
carry explicit provenance and are never generated by automation. Drafting may
quote them; it may never invent them.
"""

from __future__ import annotations

import enum
import math
import re
import uuid
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

__all__ = [
    "KBEntryKind",
    "KBEntry",
    "tokenize",
    "tfidf_rank",
    "cosine_similarity",
]

_TOKEN_RE = re.compile(r"[a-z0-9][a-z0-9+#./\-]*")
_STOPWORDS = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "by",
        "for",
        "from",
        "has",
        "have",
        "i",
        "in",
        "is",
        "it",
        "its",
        "of",
        "on",
        "or",
        "that",
        "the",
        "this",
        "to",
        "was",
        "we",
        "were",
        "will",
        "with",
        "you",
        "your",
        "our",
        "their",
        "they",
        "he",
        "she",
    }
)


class KBEntryKind(enum.StrEnum):
    PROJECT = "project"
    ACHIEVEMENT = "achievement"
    STORY = "story"  # STAR-format behavioral answer
    BLURB = "blurb"  # reusable short paragraph (summary, why-me, etc.)
    CERTIFICATION = "certification"


class KBEntry(BaseModel):
    """One reusable career entry. Created/edited only by the user."""

    model_config = ConfigDict(frozen=True)

    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    profile_id: str = Field(min_length=1)
    kind: KBEntryKind
    title: str = Field(min_length=1, max_length=200)
    body: str = Field(min_length=1, max_length=8000)
    tags: tuple[str, ...] = Field(default=())
    # User-asserted provenance: KB entries are the user's own claims about themselves.
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    times_used: int = Field(default=0, ge=0)

    @field_validator("title", "body")
    @classmethod
    def _nonblank(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("must not be blank")
        return v

    @field_validator("tags")
    @classmethod
    def _clean_tags(cls, v: tuple[str, ...]) -> tuple[str, ...]:
        return tuple(t.strip().lower() for t in v if t.strip())[:20]

    def touch_used(self) -> KBEntry:
        """Record one reuse (drafting/prep). Returns a new immutable instance."""
        now = datetime.now(UTC)
        return self.model_copy(update={"times_used": self.times_used + 1, "updated_at": now})

    def text_for_ranking(self) -> str:
        """Title + tags + body — the full signal used for TF-IDF matching."""
        return f"{self.title} {' '.join(self.tags)} {self.body}"


def tokenize(text: str) -> list[str]:
    """Lowercase word tokens minus stopwords. Keeps tech tokens (c++, c#, .net, ci/cd)."""
    return [t for t in _TOKEN_RE.findall(text.lower()) if t not in _STOPWORDS and len(t) > 1]


def cosine_similarity(a: list[str], b: list[str]) -> float:
    """Set-weighted cosine over token counts (0.0-1.0)."""
    if not a or not b:
        return 0.0
    counts_a: dict[str, int] = {}
    counts_b: dict[str, int] = {}
    for t in a:
        counts_a[t] = counts_a.get(t, 0) + 1
    for t in b:
        counts_b[t] = counts_b.get(t, 0) + 1
    common = set(counts_a) & set(counts_b)
    if not common:
        return 0.0
    dot = sum(counts_a[t] * counts_b[t] for t in common)
    norm_a = math.sqrt(sum(c * c for c in counts_a.values()))
    norm_b = math.sqrt(sum(c * c for c in counts_b.values()))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def tfidf_rank(
    entries: list[Any],
    jd_text: str,
    *,
    top_k: int = 5,
    min_score: float = 0.05,
) -> list[tuple[Any, float]]:
    """Rank KB entries against a JD by TF-IDF-style relevance.

    TF-IDF here: per-entry token frequencies weighted by inverse document
    frequency across the entry set, scored against the JD's token vector via
    cosine. Returns up to ``top_k`` (entry, score) pairs above ``min_score``,
    best first. Pure stdlib; deterministic; zero network.
    """
    if not entries or not jd_text.strip():
        return []
    n_docs = len(entries)
    doc_tokens = [tokenize(e.text_for_ranking()) for e in entries]
    jd_tokens = tokenize(jd_text)

    # IDF across the entry corpus
    df: dict[str, int] = {}
    for tokens in doc_tokens:
        for t in set(tokens):
            df[t] = df.get(t, 0) + 1
    idf = {t: math.log((n_docs + 1) / (c + 1)) + 1.0 for t, c in df.items()}

    def _vec(tokens: list[str], *, use_idf: bool) -> dict[str, float]:
        vec: dict[str, float] = {}
        for t in tokens:
            w = idf.get(t, 1.0) if use_idf else 1.0
            vec[t] = vec.get(t, 0.0) + w
        return vec

    jd_vec = _vec(jd_tokens, use_idf=True)
    scored: list[tuple[Any, float]] = []
    for entry, tokens in zip(entries, doc_tokens, strict=True):
        doc_vec = _vec(tokens, use_idf=True)
        common = set(doc_vec) & set(jd_vec)
        if not common:
            continue
        dot = sum(doc_vec[t] * jd_vec[t] for t in common)
        norm_doc = math.sqrt(sum(w * w for w in doc_vec.values()))
        norm_jd = math.sqrt(sum(w * w for w in jd_vec.values()))
        if norm_doc == 0 or norm_jd == 0:
            continue
        score = dot / (norm_doc * norm_jd)
        if score >= min_score:
            scored.append((entry, round(min(1.0, score), 4)))
    scored.sort(key=lambda pair: (-pair[1], pair[0].title))
    return scored[:top_k]
